name: rabbitmq_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  cupertino_icons: ^1.0.2
  dart_amqp: ^0.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_background_service: ^0.1.0
  flutter_bloc: ^8.0.1
  flutter_flipperkit: ^0.0.28
  get_it: ^7.2.0
  google_fonts: 2.1.1
  path: ^1.8.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
